export const INDIAN_STATES = [
  { value: 'tamil_nadu', label: 'Tamil Nadu', icon: '🕉️' },
  { value: 'andhra_pradesh', label: 'Andhra Pradesh', icon: '🙏' },
  { value: 'telangana', label: 'Telangana', icon: '🛕' },
  { value: 'karnataka', label: 'Karnataka', icon: '🪷' },
  { value: 'kerala', label: 'Kerala', icon: '🌴' },
  { value: 'maharashtra', label: 'Maharashtra', icon: '🚩' },
  { value: 'gujarat', label: 'Gujarat', icon: '🪔' },
  { value: 'west_bengal', label: 'West Bengal', icon: '🌸' },
  { value: 'uttar_pradesh', label: 'Uttar Pradesh', icon: '🛕' },
  { value: 'rajasthan', label: 'Rajasthan', icon: '🏰' },
  { value: 'madhya_pradesh', label: 'Madhya Pradesh', icon: '🐘' },
  { value: 'bihar', label: 'Bihar', icon: '🕉️' },
  { value: 'odisha', label: 'Odisha', icon: '🪷' },
  { value: 'punjab', label: 'Punjab', icon: '🙏' },
  { value: 'haryana', label: 'Haryana', icon: '🛕' },
  { value: 'other', label: 'Other', icon: '🕉️' },
] as const;

export const LANGUAGES = [
  { value: 'tamil', label: 'தமிழ் (Tamil)', icon: '🇮🇳' },
  { value: 'telugu', label: 'తెలుగు (Telugu)', icon: '🇮🇳' },
  { value: 'kannada', label: 'ಕನ್ನಡ (Kannada)', icon: '🇮🇳' },
  { value: 'malayalam', label: 'മലയാളം (Malayalam)', icon: '🇮🇳' },
  { value: 'marathi', label: 'मराठी (Marathi)', icon: '🇮🇳' },
  { value: 'gujarati', label: 'ગુજરાતી (Gujarati)', icon: '🇮🇳' },
  { value: 'bengali', label: 'বাংলা (Bengali)', icon: '🇮🇳' },
  { value: 'hindi', label: 'हिंदी (Hindi)', icon: '🇮🇳' },
  { value: 'punjabi', label: 'ਪੰਜਾਬੀ (Punjabi)', icon: '🇮🇳' },
  { value: 'odia', label: 'ଓଡ଼ିଆ (Odia)', icon: '🇮🇳' },
  { value: 'other', label: 'Other', icon: '🌍' },
] as const;

export const DEITIES = [
  { value: 'shiva', label: 'Lord Shiva', icon: '🔱', color: 'from-blue-500 to-purple-600' },
  { value: 'vishnu', label: 'Lord Vishnu', icon: '🔵', color: 'from-blue-600 to-cyan-500' },
  { value: 'krishna', label: 'Lord Krishna', icon: '🦚', color: 'from-blue-500 to-indigo-600' },
  { value: 'ganesh', label: 'Lord Ganesha', icon: '🐘', color: 'from-orange-500 to-red-500' },
  { value: 'murugan', label: 'Lord Murugan', icon: '🦚', color: 'from-red-500 to-orange-500' },
  { value: 'durga', label: 'Goddess Durga', icon: '🦁', color: 'from-red-600 to-pink-500' },
  { value: 'lakshmi', label: 'Goddess Lakshmi', icon: '🪷', color: 'from-pink-500 to-rose-500' },
  { value: 'saraswati', label: 'Goddess Saraswati', icon: '🎵', color: 'from-white to-yellow-200' },
  { value: 'hanuman', label: 'Lord Hanuman', icon: '🐒', color: 'from-orange-600 to-red-600' },
  { value: 'rama', label: 'Lord Rama', icon: '🏹', color: 'from-green-500 to-blue-500' },
  { value: 'other', label: 'Other Deities', icon: '🕉️', color: 'from-amber-500 to-orange-500' },
] as const;

export const MOCK_POSTS = [
  {
    id: '1',
    username: 'temple_devotee',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100',
    caption: 'Morning aarti at the temple 🙏 #blessed #devotion',
    mediaUrl: 'https://images.unsplash.com/photo-1609766857326-18c44f9104e6?w=800',
    likes: 1234,
    comments: 89,
    region: 'tamil_nadu',
    language: 'tamil',
    deity: 'murugan',
    timeAgo: '2h ago',
  },
  {
    id: '2',
    username: 'krishna_bhakt',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    caption: 'Radhe Krishna! Beautiful evening at Vrindavan 🦚✨',
    mediaUrl: 'https://images.unsplash.com/photo-1544552866-d3ed42536cfd?w=800',
    likes: 2567,
    comments: 156,
    region: 'uttar_pradesh',
    language: 'hindi',
    deity: 'krishna',
    timeAgo: '4h ago',
  },
  {
    id: '3',
    username: 'shiva_follower',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100',
    caption: 'Om Namah Shivaya 🔱 Mahashivratri vibes',
    mediaUrl: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=800',
    likes: 3890,
    comments: 234,
    region: 'uttar_pradesh',
    language: 'hindi',
    deity: 'shiva',
    timeAgo: '6h ago',
  },
];

export const MOCK_REELS = [
  {
    id: '1',
    username: 'devotional_vibes',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100',
    thumbnail: 'https://images.unsplash.com/photo-1609766857326-18c44f9104e6?w=400',
    caption: 'Temple bells ringing 🔔',
    likes: 12400,
    views: 89000,
    music: 'Om Jai Jagdish Hare',
    region: 'maharashtra',
  },
  {
    id: '2',
    username: 'bhakti_songs',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100',
    thumbnail: 'https://images.unsplash.com/photo-1544552866-d3ed42536cfd?w=400',
    caption: 'Krishna Bhajan 🦚',
    likes: 8900,
    views: 56000,
    music: 'Hare Krishna Mantra',
    region: 'west_bengal',
  },
  {
    id: '3',
    username: 'tamil_bhakti',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100',
    thumbnail: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=400',
    caption: 'Murugan Song 🙏',
    likes: 15600,
    views: 120000,
    music: 'Thiruppugazh',
    region: 'tamil_nadu',
  },
];

export const MOCK_MUSIC = [
  {
    id: '1',
    title: 'Thiruppugazh - Arumugan',
    artist: 'T.M. Soundararajan',
    duration: '5:23',
    coverUrl: 'https://images.unsplash.com/photo-1609766857326-18c44f9104e6?w=200',
    plays: 125000,
    region: 'tamil_nadu',
    language: 'tamil',
    deity: 'murugan',
  },
  {
    id: '2',
    title: 'Hare Krishna Mahamantra',
    artist: 'ISKCON',
    duration: '8:45',
    coverUrl: 'https://images.unsplash.com/photo-1544552866-d3ed42536cfd?w=200',
    plays: 890000,
    region: 'west_bengal',
    language: 'bengali',
    deity: 'krishna',
  },
  {
    id: '3',
    title: 'Om Namah Shivaya',
    artist: 'Shankar Mahadevan',
    duration: '6:12',
    coverUrl: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=200',
    plays: 2340000,
    region: 'maharashtra',
    language: 'marathi',
    deity: 'shiva',
  },
  {
    id: '4',
    title: 'Annamayya Keerthana',
    artist: 'S.P. Balasubrahmanyam',
    duration: '4:56',
    coverUrl: 'https://images.unsplash.com/photo-1609766857326-18c44f9104e6?w=200',
    plays: 567000,
    region: 'andhra_pradesh',
    language: 'telugu',
    deity: 'vishnu',
  },
];

export const MOCK_TEMPLES = [
  {
    id: '1',
    name: 'Meenakshi Amman Temple',
    location: 'Madurai, Tamil Nadu',
    image: 'https://images.unsplash.com/photo-1621351183012-e2f9972dd9bf?w=800',
    followers: 125000,
    deity: 'durga',
    state: 'tamil_nadu',
  },
  {
    id: '2',
    name: 'Tirumala Venkateswara',
    location: 'Tirupati, Andhra Pradesh',
    image: 'https://images.unsplash.com/photo-1609766857326-18c44f9104e6?w=800',
    followers: 890000,
    deity: 'vishnu',
    state: 'andhra_pradesh',
  },
  {
    id: '3',
    name: 'Kashi Vishwanath',
    location: 'Varanasi, Uttar Pradesh',
    image: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=800',
    followers: 456000,
    deity: 'shiva',
    state: 'uttar_pradesh',
  },
  {
    id: '4',
    name: 'Siddhivinayak Temple',
    location: 'Mumbai, Maharashtra',
    image: 'https://images.unsplash.com/photo-1544552866-d3ed42536cfd?w=800',
    followers: 678000,
    deity: 'ganesh',
    state: 'maharashtra',
  },
];

export const MOCK_GROUPS = [
  {
    id: '1',
    name: 'Tamil Bhakti Community',
    members: 45000,
    posts: 1234,
    cover: 'https://images.unsplash.com/photo-1609766857326-18c44f9104e6?w=800',
    region: 'tamil_nadu',
    deity: 'murugan',
  },
  {
    id: '2',
    name: 'Krishna Rasika Sangh',
    members: 89000,
    posts: 2567,
    cover: 'https://images.unsplash.com/photo-1544552866-d3ed42536cfd?w=800',
    region: 'west_bengal',
    deity: 'krishna',
  },
  {
    id: '3',
    name: 'Shiva Bhakts Maharashtra',
    members: 67000,
    posts: 1890,
    cover: 'https://images.unsplash.com/photo-1561731216-c3a4d99437d5?w=800',
    region: 'maharashtra',
    deity: 'shiva',
  },
];

export type IndianState = typeof INDIAN_STATES[number]['value'];
export type Language = typeof LANGUAGES[number]['value'];
export type Deity = typeof DEITIES[number]['value'];
